build/ipvsdr/Dockerfile
core/pkg/arp/cache.go
providers/ipvsdr/ipvsdr.go
providers/ipvsdr/keepalived.go

Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```

fix: avoid infinite waiting for arp request

---

Gopkg.lock
Gopkg.toml
core/pkg/net/net.go
providers/ipvsdr/ipvsdr.go
providers/ipvsdr/keepalived.go
vendor/github.com/zoumo/golib/LICENSE
vendor/github.com/zoumo/golib/netutil/net.go
vendor/k8s.io/client-go/util/retry/util.go

Fixes #
Reference to #
/cc @your-reviewer
```release-note
NONE
```

refactor(net): rewrite core/pkg/net

---

providers/ipvsdr/ipvscache.go
providers/ipvsdr/ipvsdr.go

Fixes #
Reference to #
/cc @li-ang @whalecold 
```release-note
NONE
```

fix(ipvs): wait for ipvs persistent connections cache expiring in backup nodes

---

Gopkg.lock
providers/ipvsdr/ipvscache.go
vendor/github.com/zoumo/golib/shell/shell.go
vendor/k8s.io/client-go/util/retry/util.go

Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```

refactor(ipvs): replace exec.Command with golib/shell

---

providers/ipvsdr/ipvscache.go

Fixes #
Reference to #
```release-note
NONE
```

fix(ipvs): skip connections cache checking in master

---

providers/ipvsdr/ipvscache.go

Fixes #
Reference to #
```release-note
NONE
```

refactor: reading connections from file instead of ipvsadm

---

core/provider/controller.go

fix(machine): delete machine infomer sync
Fixes #
Reference to #
/cc @zoumo
```release-note
NONE
```

fix(machine): delete machine infomer sync

---

providers/azure/azure.go

fix(failed): delete finalizer though azure lb if empty
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```

[CPS-940]  fix(failed): delete finalizer though azure lb if empty

---

providers/ipvsdr/ipvsdr.go

the priority for each node is always 100 because the node name is always in the first place by the following code
```
resolvedNodes = []string{p.nodeIP.String()}
```
we must sort it before calculating priority. 
Fixes #
Reference to #
```release-note
NONE
```

fix: correct node priority in vrrp

---

OWNERS

chore: add owner
Fixes #
Reference to #
/cc @your-reviewer
```release-note
NONE
```

chore: add owner

---

cmd/azure/main.go
core/provider/controller.go
core/provider/types.go
providers/azure/appgateway.go
providers/azure/azure.go
providers/azure/client/client.go
providers/azure/client/types.go
providers/azure/utils.go

feat(appgateway): add azure application gateway function for kaide
Fixes 
Reference to caicloud/service#770
/cc @whalecold @hanxueluo 
```release-note
NONE
```

feat(appgateway): add azure application gateway function for kaide

---

providers/azure/appgateway.go
providers/azure/azure.go

feat(appgateway): add app gateway http setting and probe
Fixes #
Reference to caicloud/service#770
```release-note
NONE
```

feat(appgateway): add app gateway http setting and probe

---

providers/azure/appgateway.go

fix(appgateway): fix probe id not found bug
Fixes #
Reference to #
```release-note
NONE
```

[KAIDE-14]fix(appgateway): fix probe id not found bug

---

providers/azure/appgateway.go
providers/azure/azure.go
providers/azure/utils.go

fix(appgateway): fix delete rule error
Fixes #
Reference to #
```release-note
NONE
```

[KAIDE-18]fix(appgateway): fix delete rule error

---

cmd/azure/main.go
cmd/ingress/main.go
cmd/ipvsdr/main.go
core/pkg/arp/cache.go
core/pkg/arp/cache_linux.go
core/provider/controller.go
pkg/execd/execd.go
providers/azure/azure.go
providers/azure/loadbalancer.go
providers/azure/utils.go
providers/ingress/sidecar.go
providers/ipvsdr/ipvscache.go
providers/ipvsdr/ipvsdr.go
providers/ipvsdr/keepalived.go
providers/ipvsdr/util.go

修复 lint 错误
Fixes #
Reference to #
/cc @hanxueluo @hicaistar 
```release-note
NONE
```

refactor: fix lint code

---

Makefile

Automatically submit by tool file-sync, author by @bbbmj
/cc
```release-note
NONE
```

feat(*): upgrade golang image to 1.13-security

---

Makefile

Fixes #
Reference to # http://jira.caicloud.xyz/browse/CPS-8648
/cc @hicaistar 
```release-note
NONE
```

feat(*): upgrade golang image to 1.12-security

---

providers/f5lb/common.go
providers/f5lb/f5dns.go
providers/f5lb/f5lb.go
providers/f5lb/f5ltm.go

Fixes #
Reference to # @hanxueluo 
/cc @your-reviewer
```release-note
NONE
```

style: define const layer4, layer7

---

providers/f5lb/f5ltm.go

create pool and node in the same partition with virtual server
Fixes #
Reference to #
/cc @hanxueluo 
```release-note
NONE
```

feature(f5ltm): support f5ltm partition

---

build/ingress/Dockerfile

对于这类需要访问其他 vlan 的 pod，由于使用的网络是节点网络，路由和169的虚拟网卡冲突，需要使这类流量走节点的默认路由，而不是169的网卡，通过iptable 的 owner 模块实现，这个 repo 里需要为该 uid 修改文件权限
Fixes #
Reference to #
/cc @your-reviewer
```release-note
NONE
```

feat(guosen):add permission for specifial uid
